lyrics_game/api/urls.py
from django.urls import include, path
from rest_framework import routers

from .views import ArtistViewSet

router = routers.DefaultRouter()
router.register(r'artist', ArtistViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

lyrics_game/lyrics_game/urls.py
from django.contrib import admin
from django.urls import include, path

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cms/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),
    path('music/', include('music.urls')),
    path('api/', include('api.urls')),
    path('', include(wagtail_urls)),
]

lyrics_game/music/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('artiste/', views.artiste_view, name='artiste'),
    path('guess/', views.guess_artist, name='guess_artist'),
    path('get_hint/', views.get_hint, name='get_hint'),

    path('titre/', views.titre_view, name='titre'),
    path('guess_title/', views.guess_title, name='guess_title'),
    path('get_hint_title/', views.get_hint_title, name='get_hint_title'),

    path('juste_artiste/', views.juste_artiste_view, name='juste_artiste'),
    path('guess_juste_artiste/', views.guess_juste_artiste, name='guess_juste_artiste'),
    path('get_hint_juste_artiste/', views.get_hint_juste_artiste, name='get_hint_juste_artiste'),

    path('lyrics/', views.lyrics_quiz, name='lyrics'),
    path('lyrics_game/', views.lyrics_game_view, name='lyrics_game'),
]

lyrics_game/music/models.py
from django.db import models
from wagtail.admin.panels import FieldPanel, MultiFieldPanel
from wagtail.fields import RichTextField
from wagtail.models import Page


class Song(models.Model):
    title = models.CharField(max_length=100)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    lyrics = models.TextField()
    answer = models.CharField(max_length=200, blank=True)
    # string array
    songs = models.JSONField(default=list)

    def __str__(self):
        return self.name, ' - ', self.songs, ' songs'


class ArtistPage(Page):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    content_panels = Page.content_panels + [
        FieldPanel('artist')
    ]


class HomePage(Page):
    buttonGuessTitle = models.CharField(max_length=100, blank=True)
    buttonGuessArtist = models.CharField(max_length=100, blank=True)
    buttonGuessLyrics = models.CharField(max_length=100, blank=True)
    buttonGuessLyricsFill = models.CharField(max_length=100, blank=True)
    buttonGuessTitleAndArtist = models.CharField(max_length=100, blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('buttonGuessTitle'),
        FieldPanel('buttonGuessArtist'),
        FieldPanel('buttonGuessLyrics'),
        FieldPanel('buttonGuessLyricsFill'),
        FieldPanel('buttonGuessTitleAndArtist')
    ]

lyrics_game/music/forms.py
# music/forms.py
from django import forms

class LyricsForm(forms.Form):
    user_input = forms.CharField(label='Complete the lyrics', max_length=100)
    random_word = forms.CharField(widget=forms.HiddenInput())
    words_around = forms.CharField(widget=forms.HiddenInput())


class LyricsGameForm(forms.Form):
    user_input = forms.CharField(label='Guess the word', max_length=100)

lyrics_game/music/views.py
# views.py

from django.http import JsonResponse
from django.shortcuts import render, redirect
from .utils import get_artist, clean_lyrics2, get_words
from .utils import get_artist, remove_random_word, process_lyrics, reveal_word
from .forms import LyricsForm, LyricsGameForm
old_singer =""
old_song_name = ""

def artiste_view(request):
    artist_data = get_artist()
    cleaned_lyrics = clean_lyrics2(artist_data['lyrics'])
    cleaned_lyrics = get_words(cleaned_lyrics)
    context = {
        'lyrics': cleaned_lyrics,
        'correct_artist': artist_data['artist'],
        'correct_title': artist_data['title']
    }
    return render(request, 'page/artiste.html', context)


def guess_artist(request):
    if request.method == 'POST':
        artist_guess = request.POST.get('artist_guess').strip().lower()
        title_guess = request.POST.get('title_guess').strip().lower()

        correct_artist = request.POST.get('correct_artist').strip().lower()
        correct_title = request.POST.get('correct_title').strip().lower()

        if artist_guess == correct_artist and title_guess == correct_title:
            message = "Bravo, vous avez deviné correctement !"
        else:
            message = "Désolé, ce n'est pas la bonne réponse."

        return JsonResponse({'message': message})

    return JsonResponse({'message': 'Invalid request'}, status=400)


def get_hint(request):
    if request.method == 'GET':
        correct_artist = request.GET.get('correct_artist')
        correct_title = request.GET.get('correct_title')
        hint_type = request.GET.get('hint_type')
        hint_index = int(request.GET.get('hint_index', 0))

        if hint_type == 'artist':
            if hint_index < len(correct_artist):
                hint = correct_artist[:hint_index + 1]
                hint_index += 1
            else:
                hint = "Aucun autre indice disponible."
                hint_index = len(correct_artist)
        elif hint_type == 'title':
            if hint_index < len(correct_title):
                hint = correct_title[:hint_index + 1]
                hint_index += 1
            else:
                hint = "Aucun autre indice disponible."
                hint_index = len(correct_title)

        return JsonResponse({'hint': hint, 'hint_index': hint_index})

    return JsonResponse({'message': 'Invalid request'}, status=400)


def titre_view(request):
    artist_data = get_artist()
    cleaned_lyrics = clean_lyrics2(artist_data['lyrics'])
    cleaned_lyrics = get_words(cleaned_lyrics)
    context = {
        'lyrics': cleaned_lyrics,
        'correct_artist': artist_data['artist'],
        'correct_title': artist_data['title']
    }
    return render(request, 'page/titre.html', context)


def guess_title(request):
    if request.method == 'POST':
        title_guess = request.POST.get('title_guess').strip().lower()

        correct_title = request.POST.get('correct_title').strip().lower()

        if title_guess == correct_title:
            message = "Bravo, vous avez deviné correctement !"
        else:
            message = "Désolé, ce n'est pas la bonne réponse."

        return JsonResponse({'message': message})

    return JsonResponse({'message': 'Invalid request'}, status=400)


def get_hint_title(request):
    if request.method == 'GET':
        correct_title = request.GET.get('correct_title')
        hint_type = request.GET.get('hint_type')
        hint_index = int(request.GET.get('hint_index', 0))

        if hint_type == 'title':
            if hint_index < len(correct_title):
                hint = correct_title[:hint_index + 1]
                hint_index += 1
            else:
                hint = "Aucun autre indice disponible."
                hint_index = len(correct_title)

        return JsonResponse({'hint': hint, 'hint_index': hint_index})

    return JsonResponse({'message': 'Invalid request'}, status=400)


def juste_artiste_view(request):
    artist_data = get_artist()
    cleaned_lyrics = clean_lyrics2(artist_data['lyrics'])
    cleaned_lyrics = get_words(cleaned_lyrics)

    context = {
        'lyrics': cleaned_lyrics,
        'correct_artist': artist_data['artist'],
        'correct_title': artist_data['title']
    }
    return render(request, 'page/juste_artiste.html', context)


def guess_juste_artiste(request):
    if request.method == 'POST':
        artist_guess = request.POST.get('artist_guess').strip().lower()

        correct_artist = request.POST.get('correct_artist').strip().lower()

        if artist_guess == correct_artist:
            message = "Bravo, vous avez deviné correctement !"
        else:
            message = "Désolé, ce n'est pas la bonne réponse."

        return JsonResponse({'message': message})

    return JsonResponse({'message': 'Invalid request'}, status=400)


def get_hint_juste_artiste(request):
    if request.method == 'GET':
        correct_artist = request.GET.get('correct_artist')
        hint_type = request.GET.get('hint_type')
        hint_index = int(request.GET.get('hint_index', 0))

        if hint_type == 'artist':
            if hint_index < len(correct_artist):
                hint = correct_artist[:hint_index + 1]
                hint_index += 1
            else:
                hint = "Aucun autre indice disponible."
                hint_index = len(correct_artist)

        return JsonResponse({'hint': hint, 'hint_index': hint_index})

    return JsonResponse({'message': 'Invalid request'}, status=400)

def lyrics_quiz(request):
    global old_singer
    global old_song_name
    while True:
        information = get_artist()
        lyrics = information['lyrics']
        singer = information['artist']
        song_name = information['title']
        if lyrics is not None and len(lyrics) > 0:
            break

    if request.method == 'POST':
        form = LyricsForm(request.POST)
        if form.is_valid():
            user_input = form.cleaned_data['user_input']
            answer = form.cleaned_data['random_word']
            if user_input.strip().lower() == answer.lower():
                result = 'Bravo, vous avez deviné correctement !'
                result_color = 'green'
            else:
                result = "Désolé, ce n'est pas la bonne réponse."
                result_color = 'red'
            words_around = form.cleaned_data['words_around']
            singer = old_singer
            song_name = old_song_name
        else:
            result = ''
            result_color = ''
            words_around = ""
            answer = ""
    else:
        old_singer = singer
        old_song_name = song_name
        answer, words_around = remove_random_word(lyrics)
        form = LyricsForm(initial={'random_word': answer, 'words_around': words_around})
        result = ''
        result_color = ''

    return render(request, 'page/complete_lyrics.html', {
        'form': form,
        'lyrics': words_around,
        'result': result,
        'result_color': result_color,
        'answer': answer,
        'singer': singer,
        'song_name': song_name
    })


def lyrics_game_view(request):
    if 'change_song' in request.POST:
        if 'song_name' in request.session:
            del request.session['words']
            del request.session['processed_lyrics']
            del request.session['singer']
            del request.session['song_name']
        return redirect('lyrics_game') 

    singer = None
    song_name = None
    lyrics = None

    if 'song_name' not in request.session:
        while lyrics is None:
            information = get_artist()
            lyrics = information['lyrics']
            singer = information['artist']
            song_name = information['title']
        
        words, processed_lyrics = process_lyrics(lyrics)
        request.session['words'] = words
        request.session['processed_lyrics'] = processed_lyrics
        request.session['singer'] = str(singer)
        request.session['song_name'] = song_name
    else:
        singer = request.session['singer']
        song_name = request.session['song_name']
        words = request.session['words']
        processed_lyrics = request.session['processed_lyrics']

    win = False
    if request.method == 'POST':
        form = LyricsGameForm(request.POST)
        if form.is_valid():
            guess = form.cleaned_data['user_input']
            processed_lyrics = reveal_word(words, processed_lyrics, guess)
            request.session['processed_lyrics'] = processed_lyrics
            if '_' not in processed_lyrics:
                win = True
    else:
        form = LyricsGameForm()

    context = {
        'form': form,
        'processed_lyrics': ' '.join(processed_lyrics),
        'singer': singer,
        'song_name': song_name,
        'win': win,
        'words': words,
    }

    return render(request, 'page/lyrics_game.html', context)

lyrics_game/music/templates/page/artiste.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trouver l'artiste et le titre</title>
    <link rel="stylesheet" href="files/styles_artiste.css">

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            height: 100vh;
            justify-content: center;
            align-items: center;
        }

        .container {
            display: flex;
            width: 90%;
            max-width: 1200px;
            height: 80%;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            overflow: hidden;
            margin: 1% 0;
        }

        .left-column {
            flex: 2;
            padding: 20px;
            overflow-y: auto;
        }

        .right-column {
            flex: 1;
            padding: 20px;
            background-color: #f8f9fa;
            border-radius: 10px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        h1 {
            color: #333;
            font-size: 2em;
            margin-bottom: 10px;
        }

        p {
            font-size: 1.2em;
            line-height: 1.6;
            color: #666;
            margin-bottom: 20px;
            text-align: justify;
        }

        form {
            display: flex;
            flex-direction: column;
            width: 100%;
            max-width: 400px;
        }

        input[type="text"] {
            width: 90%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 1em;
        }

        button[type="submit"] {
            width: 96%;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 1em;
            cursor: pointer;
            transition: background-color 0.3s, color 0.3s;
        }

        button[type="submit"]:hover {
            background-color: #0056b3;
        }

        .back-link {
            position: absolute;
            top: 20px;
            left: 20px;
            text-decoration: none;
            color: #007bff;
            font-weight: bold;
            padding: 10px 20px;
            border: 2px solid #007bff;
            border-radius: 5px;
            background-color: #e6e6e6;
            transition: background-color 0.3s, color 0.3s;
        }

        .back-link:hover {
            background-color: #007bff;
            color: #e6e6e6;
        }

        .popup {
            display: none;
            position: fixed;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
            z-index: 1000;
        }

        .popup button, #newGameButton {
            margin-top: 10px;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 1em;
            cursor: pointer;
            transition: background-color 0.3s, color 0.3s;
        }

        .popup button:hover,  #newGameButton:hover {
            background-color: #0056b3;
        }

        .popup-overlay {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.5);
            z-index: 999;
        }

        .hint-button {
            width: 100%;
            padding: 10px 20px;
            background-color: #6c757d;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 1em;
            cursor: pointer;
            transition: background-color 0.3s, color 0.3s;
            margin-bottom: 10px;
        }

        .hint-button:hover {
            background-color: #495057;
        }

        /* Positionnement des boutons d'indice en bas */
        .hint-buttons {
            margin-top: auto; /* Les place en bas du conteneur */
            display: flex;
            flex-direction: column;
            align-items: center;
        }
    </style>
</head>
<body>
    <a class="back-link" href="../../">&lt; Retour à l'accueil</a>
    <img src="../../../static/logoLQ.png" alt="Artiste" style="width: 10%; margin-top: 1%;">
    <h1>Trouver l'artiste et le titre de la chanson :</h1>
    <div class="container">
        <div class="left-column">
            {% for lyric in lyrics %}
                <p>{{ lyric }}</p>
            {% endfor %}
        </div>
        <div class="right-column">
            <form id="guessForm" action="{% url 'guess_artist' %}" method="post">
                {% csrf_token %}
                <input type="text" name="artist_guess" placeholder="Artiste" required>
                <input type="text" name="title_guess" placeholder="Titre de la chanson" required>
                <input type="hidden" name="correct_artist" value="{{ correct_artist }}">
                <input type="hidden" name="correct_title" value="{{ correct_title }}">
                <button type="submit">Soumettre</button>
            </form>
            <p id="hintArtistText"></p>
            <p id="hintTitleText"></p>
            <div class="hint-buttons">
                <button id="hintArtistButton" class="hint-button">Indice Artiste</button>
                <button id="hintTitleButton" class="hint-button">Indice Titre</button>
            </div>
            <button id="newGameButton" onclick="retry()">Nouvelle partie</button>
        </div>
    </div>

    <div id="popupOverlay" class="popup-overlay"></div>
    <div id="popup" class="popup">
        <p id="popupMessage"></p>
        <button id="closeButton" onclick="closePopup()">Réessayer</button>
        <button id="revealAnswerButton" style="display: none;" onclick="revealAnswer()">Afficher la réponse</button>
        <button id="closeButton2" onclick="retry()">Fermer</button>
        <button id="retryButton" style="display: none;" onclick="retry()">Recommencer</button>
    </div>

    <script>
        let hintArtistIndex = 0;
        let hintTitleIndex = 0;
        const correctArtist = "{{ correct_artist }}";
        const correctTitle = "{{ correct_title }}";
        const artistHints = Array.from(correctArtist).map((char, i) => correctArtist.slice(0, i + 1));
        const titleHints = Array.from(correctTitle).map((char, i) => correctTitle.slice(0, i + 1));

        document.getElementById('guessForm').addEventListener('submit', function(event) {
            event.preventDefault();
            var formData = new FormData(this);

            fetch("{% url 'guess_artist' %}", {
                method: 'POST',
                body: formData,
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
            .then(response => response.json())
            .then(data => {
                document.getElementById('popupMessage').innerText = data.message;

                if (data.message.includes('Bravo')) {
                    document.getElementById('retryButton').style.display = 'inline-block';
                    document.getElementById('revealAnswerButton').style.display = 'none';
                    document.getElementById('closeButton2').style.display = 'none';
                    document.getElementById('closeButton').style.display = 'none';
                } else {
                    document.getElementById('revealAnswerButton').style.display = 'inline-block';
                    document.getElementById('retryButton').style.display = 'none';
                    document.getElementById('closeButton2').style.display = 'none';
                }

                document.getElementById('popup').style.display = 'inline-block';
                document.getElementById('popupOverlay').style.display = 'inline-block';
            });
        });

        document.getElementById('hintArtistButton').addEventListener('click', function() {
            if (hintArtistIndex < artistHints.length) {
                document.getElementById('hintArtistText').innerText = "Indice Artiste: " + artistHints[hintArtistIndex];
                hintArtistIndex++;
            }
        });

        document.getElementById('hintTitleButton').addEventListener('click', function() {
            if (hintTitleIndex < titleHints.length) {
                document.getElementById('hintTitleText').innerText = "Indice Titre: " + titleHints[hintTitleIndex];
                hintTitleIndex++;
            }
        });

        function closePopup() {
            document.getElementById('popup').style.display = 'none';
            document.getElementById('popupOverlay').style.display = 'none';
        }

        function revealAnswer() {
            document.getElementById('popupMessage').innerText = "La bonne réponse était : " + correctArtist + " - " + correctTitle;
            document.getElementById('revealAnswerButton').style.display = 'none';
            document.getElementById('closeButton').style.display = 'none';
            document.getElementById('closeButton2').style.display = 'inline-block';
        }

        function retry() {
            window.location.reload();
        }

    </script>
</body>
</html>

lyrics_game/music/templates/page/complete_lyrics.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Trouver le mot manquant</title>
    <link rel="stylesheet" href="files/styles_artiste.css">

    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            height: 100vh;
            justify-content: center;
            align-items: center;
        }
    
        .container {
            display: flex;
            width: 90%;
            max-width: 1200px;
            height: 80%;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            overflow: hidden;
            margin: 1% 0;
        }
    
        .left-column {
            flex: 2;
            padding: 20px;
            overflow-y: auto;
        }
    
        .right-column {
            flex: 1;
            padding: 20px;
            background-color: #f8f9fa;
            border-radius: 10px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
    
        h1 {
            color: #333;
            font-size: 2em;
            margin-bottom: 10px;
        }
    
        p {
            font-size: 1.2em;
            line-height: 1.6;
            color: #666;
            margin-bottom: 20px;
            text-align: justify;
        }
    
        form {
            display: flex;
            flex-direction: column;
            width: 100%;
            max-width: 400px;
        }
    
        label {
            font-size: 1em;
            margin-bottom: 5px;
            color: #333;
        }
    
        input[type="text"] {
            width: 90%;
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 5px;
            font-size: 1em;
        }
    
        input[type="submit"] {
            width: 100%;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 1em;
            cursor: pointer;
            transition: background-color 0.3s, color 0.3s;
            margin-top: 10px;
        }
    
        input[type="submit"]:hover {
            background-color: #0056b3;
        }
    
        .back-link {
            position: absolute;
            top: 20px;
            left: 20px;
            text-decoration: none;
            color: #007bff;
            font-weight: bold;
            padding: 10px 20px;
            border: 2px solid #007bff;
            border-radius: 5px;
            background-color: #e6e6e6;
            transition: background-color 0.3s, color 0.3s;
        }
    
        .back-link:hover {
            background-color: #007bff;
            color: #e6e6e6;
        }
    
        .popup {
            display: none;
            position: fixed;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
            z-index: 1000;
        }
    
        .popup button {
            margin-top: 10px;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 1em;
            cursor: pointer;
            transition: background-color 0.3s, color 0.3s;
        }
    
        .popup button:hover {
            background-color: #0056b3;
        }
    
        .popup-overlay {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.5);
            z-index: 999;
        }
    
        .hint-button {
            width: 100%;
            padding: 10px 20px;
            background-color: #6c757d;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 1em;
            cursor: pointer;
            transition: background-color 0.3s, color 0.3s;
            margin-bottom: 10px;
        }
    
        .hint-button:hover {
            background-color: #495057;
        }
    
        /* Positionnement des boutons d'indice en bas */
        .hint-buttons {
            margin-top: auto;
            /* Les place en bas du conteneur */
            display: flex;
            flex-direction: column;
            align-items: center;
        }
    
        #show-answer {
            width: 100%;
            padding: 10px 20px;
            background-color: #6c757d;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 1em;
            cursor: pointer;
            transition: background-color 0.3s, color 0.3s;
            margin-top: auto;
            margin-bottom: 10px;
        }
    
        #show-answer:hover {
            background-color: #495057;
        }
    
        form[method="get"] button[type="submit"] {
            width: 100%;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            font-size: 1em;
            cursor: pointer;
            transition: background-color 0.3s, color 0.3s;
        }
    
        form[method="get"] button[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
    
</head>

<body>
    <a class="back-link" href="../../">&lt; Retour à l'accueil</a>
    <img src="../../../static/logoLQ.png" alt="Artiste" style="width: 10%; margin-top: 1%;">
    <h1>Trouver le mot manquant :</h1>
    <div class="container">
        <div class="left-column">
            <p id="lyric-complete" class="lyric-text">{{ lyrics|safe }}</p>
        </div>
        <div class="right-column">
            <h2> {{ singer|safe }} : {{ song_name|safe }} </h2>
            <form class="quiz-form" id="lyrics-form" method="post">
                {% csrf_token %}
                <label for="id_user_input">Parole manquante :</label>
                {{ form.user_input }}
                {{ form.random_word }}
                {{ form.words_around }}
                <input type="submit" value="Soumettre">
            </form>
            <p id="response"></p>
            <button id="show-answer">Afficher la réponse</button>
            <form method="get">
                <button type="submit">Nouvelle partie</button>
            </form>
            {% if result %}
            <p id="lyrics-result" style="color: {{ result_color }};">{{ result }}</p>
            {% endif %}

        </div>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            document.getElementById('show-answer').addEventListener('click', function () {
                document.getElementById('response').innerText = '{{ answer }}';
            });
        });
    </script>
</body>

</html>